FROM python:3.10-slim

# Add repository code
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY requirements-dagster.txt $DAGSTER_HOME
 
WORKDIR $DAGSTER_HOME

RUN pip install -r requirements-dagster.txt

COPY /dagster_energy $DAGSTER_HOME/dagster_energy

# Run dagster gRPC server on port 4000

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "dagster_energy"]